- name: User Setup
  hosts: itfun
  vars:
    n_users: 4
    users: "{{ ['user'] | product(range(1, n_users + 1)) | map('join') | list }}"
  tasks:
  - name: Add Users
    ansible.builtin.user:
      name: "{{ item }}"
      password: "*"
      shell: /bin/bash
    loop: "{{ users }}"
    become: true
  - name: Create .ssh Directory
    ansible.builtin.file:
      path: "/home/{{ item }}/.ssh"
      state: "directory"
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: "700"
    loop: "{{ users }}"
    become: true
  - name: Create Keys
    community.crypto.openssh_keypair:
      path: "/home/{{ item }}/.ssh/id_ssh_ed25519"
      type: "ed25519"
      regenerate: "full_idempotence"
      owner: "{{ item }}"
      group: "{{ item }}"
    loop: "{{ users }}"
    become: true
  - name: Slurp Public Keys
    ansible.builtin.slurp:
      src: "/home/{{ item }}/.ssh/id_ssh_ed25519.pub"
    register: public_keys
    loop: "{{ users }}"
    become: true
  - name: Configure authorized_keys
    ansible.builtin.lineinfile:
      path: "/home/{{ item.item }}/.ssh/authorized_keys"
      line: "{{ item.content | b64decode | trim }}"
      create: true
      owner: "{{ item.item }}"
      group: "{{ item.item }}"
      mode: "600"
    loop: "{{ public_keys.results }}"
    become: true
